# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cake Action
        # You may pin to the exact commit or the version.
        # uses: cake-build/cake-action@ada1055e59e6ae62905b178090e9636e96e54a35
        uses: devlead/cake-action@feature/gh-26
        with:
          # The path of the Cake script to run.
          #script-path: # optional, default is build.cake
          # The name of the task to execute. Note that this argument must be supported by the script.
          #target: # optional
          # The verbosity level with which to run the script. Valid values are: Quiet, Minimal, Normal, Verbose or Diagnostic.
          verbosity: diagnostic
          # Tells Cake to do a dry run of the script.
          #dry-run: # optional, default is false
          # Any custom parameters to pass to the script. Multiple parameters are defined on separate lines.
          #arguments: # optional
          # The version of Cake to install.
          #cake-version: tool-manifest
          # Flag for if Cake modules should be installed/bootstrapped.
          #cake-bootstrap: # optional, default is false
